{% set name = "flake8-pytest-style" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 919c328cacd4bc4f873ea61ab4db0d8f2c32e0db09a3c73ab46b1de497556464

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - flake8-plugin-utils >=1.3.2,<2.0.0
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - flake8_pytest_style
    - flake8_pytest_style.visitors
  commands:
    - pip check
    - flake8 --version | grep flake8-pytest-style
  requires:
    - flake8
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/flake8-pytest-style
  summary: A flake8 plugin checking common style issues or inconsistencies with pytest-based tests.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
